name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["*"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade pip
      - run: pip install .[dev]
      - run: ruff check src/flamemirror tests

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade pip
      - run: pip install .[dev]
      - run: mypy src/flamemirror

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade pip
      - run: pip install .[dev]
      - run: pytest --cov=flamemirror --cov-report=xml --cov-report=term

  coverage-gate:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: python -m pip install coverage[toml]
      - name: Enforce coverage threshold
        run: |
          coverage xml -i
          python - <<'PY'
import xml.etree.ElementTree as ET
from pathlib import Path

coverage_file = Path('coverage.xml')
if not coverage_file.exists():
    raise SystemExit('coverage.xml not found')

root = ET.parse(coverage_file).getroot()
line_rate = float(root.attrib['line-rate'])
threshold = 0.90
if line_rate < threshold:
    raise SystemExit(f"Coverage {line_rate:.2%} is below threshold {threshold:.0%}")
print(f"Coverage gate passed: {line_rate:.2%}")
PY
